server:
  port: 8100

spring:
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://messages-db:27017/microservices-messages
  application:
    name: messages

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  registration:
    enabled: true
    preferIpAddress: true