eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  registration:
    enabled: true
    preferIpAddress: true

server:
  port: 8010

spring:
  application:
    name: posts
  config:
    import: optional:configserver:http://localhost:8888
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect