spring:
  application:
    name: users
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  registration:
    enabled: true
    preferIpAddress: true
jwt:
  secret: mysupersecretkeymysupersecretkeymysupersecretkey
server:
  port: 8020