spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: discovery

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8761
